apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourceOverride
metadata:
  name: cluster-name-member01
spec:
  clusterResourceSelectors:
    - group: apps
      kind: Deployment
      version: v1
      name: sample-backend
  policy:
    overrideRules:
      - clusterSelector:
          clusterSelectorTerms:
            - labelSelector:
                matchLabels:
                  environment: staging
        jsonPatchOverrides:
          - op: replace
            path: /spec/template/spec/containers/0/env/0/value
            value: "member-01 (staging)"
---
apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourceOverride
metadata:
  name: cluster-name-member02
spec:
  clusterResourceSelectors:
    - group: apps
      kind: Deployment
      version: v1
      name: sample-backend
  policy:
    overrideRules:
      - clusterSelector:
          clusterSelectorTerms:
            - labelSelector:
                matchLabels:
                  environment: prod
        jsonPatchOverrides:
          - op: replace
            path: /spec/template/spec/containers/0/env/0/value
            value: "member-02 (prod)"
